import type { Config } from './environment.schemas';

export const renderConfigTemplate = (defaultConfig: Config): string =>
  // Renders a TypeScript configuration file template based on the provided configuration object.
  `import type { Config } from 'contract';

const contractConfig: Config = {
  ${Object.keys(defaultConfig)
    .map((key) => `${key}: ${JSON.stringify((defaultConfig as any)[key])},`)
    .join('\n  ')}
};

export default contractConfig;
`;

export const renderManifestTemplate = (contractName: string): string =>
  // Renders a TypeScript manifest file template for the specified contract.
  `// This file is automatically generated for the ${contractName} contract.
// Important: never re-export from index.ts — use direct file exports.


`;
